class EnvironmentSettings:
    def __init__(self):
        self.workspace_dir = '/data/code_Lon/VLT/HIPB_up_large'    # Base directory for saving network checkpoints.
        self.tensorboard_dir = '/data/code_Lon/VLT/HIPB_up_large/tensorboard'    # Directory for tensorboard files.
        self.pretrained_networks = '/data/code_Lon/VLT/HIPB_up_large/pretrained_networks'
        self.lasot_dir = '/share/home/u2415063035/training_dataset/LaSOT'
        self.got10k_dir = '/data/code_Lon/VLT/HIPB_up_large/data/got10k/train'
        self.vasttrack_dir='/share/home/u2415423004/training_dataset/VastTrack'
        self.got10k_val_dir = '/data/code_Lon/VLT/HIPB_up_large/data/got10k/val'
        self.lasot_lmdb_dir = '/data/code_Lon/VLT/HIPB_up_large/data/lasot_lmdb'
        self.got10k_lmdb_dir = '/data/code_Lon/VLT/HIPB_up_large/data/got10k_lmdb'
        self.trackingnet_dir = '/data/code_Lon/VLT/HIPB_up_large/data/trackingnet'
        self.trackingnet_lmdb_dir = '/data/code_Lon/VLT/HIPB_up_large/data/trackingnet_lmdb'
        self.coco_dir = '/data/code_Lon/VLT/HIPB_up_large/data/coco'
        self.coco_lmdb_dir = '/data/code_Lon/VLT/HIPB_up_large/data/coco_lmdb'
        self.lvis_dir = ''
        self.sbd_dir = ''
        self.imagenet_dir = '/data/code_Lon/VLT/HIPB_up_large/data/vid'
        self.imagenet_lmdb_dir = '/data/code_Lon/VLT/HIPB_up_large/data/vid_lmdb'
        self.imagenetdet_dir = ''
        self.ecssd_dir = ''
        self.hkuis_dir = ''
        self.msra10k_dir = ''
        self.davis_dir = ''
        self.youtubevos_dir = ''